# Generated by Django 2.2 on 2022-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0002_auto_20220808_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unqiue': '이미 사용중인 닉네임입니다.'}, max_length=15, null=True, unique=True),
        ),
    ]
